version: 2
jobs:
  pr:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      #Checkout
      - checkout
            
      # Run Build command
      - type: shell
        name: Build & Deploy PR
        command: |
          if [[ -z "$CIRCLE_PR_NUMBER" ]]
          then
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          bundle install
          bundle exec jekyll build
          cd _site
          aws s3 sync --delete . s3://sunbird-docs-qa/docs-pr/$CIRCLE_PR_NUMBER/
          fi
          
workflows:
  version: 2
  docs-version-build-deploy:
    jobs:
      - pr
