version: 2
jobs:
  staging:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      #Checkout
      - checkout
            
      # Run Build command
      - type: shell
        name: Build & Deploy
        command: |
          if [ "$CIRCLE_BRANCH" != "toc" ]
          then
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          bundle install
          bundle exec jekyll build
          cd _site
          ls  
          aws s3 cp index.html s3://sunbird-docs-qa/staging/index.html
          aws s3 sync --delete css/. s3://sunbird-docs-qa/staging/css/
          aws s3 sync --delete js/. s3://sunbird-docs-qa/staging/js/
          aws s3 sync --delete img/. s3://sunbird-docs-qa/staging/img/
          fi
workflows:
  version: 2
  toc-build-deploy:
    jobs:
      - staging
      - hold:
          type: approval
          requires:
              - staging
      - prod:
          requires:
              - hold
