version: 2
jobs:
  staging:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      #Checkout
      - checkout
            
      # Run Build command
      - type: shell
        name: Build & Deploy
        command: |
          if [ "$CIRCLE_BRANCH" != "toc" ]
          then
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          bundle exec jekyll build
          ls
          cd _site
          ls
          fi
workflows:
  version: 2
  toc-build-deploy:
    jobs:
      - staging
      - hold:
          type: approval
          requires:
              - staging
      - prod:
          requires:
              - hold
