version: 2
jobs:
  staging:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      #Checkout
      - checkout
            
      # Run Build command
      - type: shell
        name: Build & Deploy
        command: |
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          echo "CommitId: $CIRCLE_COMMIT_ID" >> _config.yml
          cat _config.yml
          ls
workflows:
  version: 2
  toc-build-deploy:
    jobs:
      - staging:
          filters:
            branches:
              only: toc
      - hold:
          type: approval
          requires:
              - staging
          filters:
            branches:
              only: toc
      - prod:
          requires:
              - hold
          filters:
            branches:
              only: toc
